// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeFtSKKp5lG34QziiYdJvg-7XO-6TZQQM',
    appId: '1:863346724834:web:05485c54429b24eb89f3bb',
    messagingSenderId: '863346724834',
    projectId: 'personal-portfolio-70dcc',
    authDomain: 'personal-portfolio-70dcc.firebaseapp.com',
    storageBucket: 'personal-portfolio-70dcc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHHMXBqzWBHaPa9Dba0FOc6joXH8w9GmA',
    appId: '1:863346724834:android:c05d5be142fb6a6b89f3bb',
    messagingSenderId: '863346724834',
    projectId: 'personal-portfolio-70dcc',
    storageBucket: 'personal-portfolio-70dcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhv9KPGTKFsSZ5lBFc8BUt1Z9sKHUMRBw',
    appId: '1:863346724834:ios:fa6543b7fdc53f8289f3bb',
    messagingSenderId: '863346724834',
    projectId: 'personal-portfolio-70dcc',
    storageBucket: 'personal-portfolio-70dcc.appspot.com',
    iosClientId: '863346724834-8djct4j6pv9cf1d3vklra0oe8ak01ln4.apps.googleusercontent.com',
    iosBundleId: 'com.mnl.personalPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhv9KPGTKFsSZ5lBFc8BUt1Z9sKHUMRBw',
    appId: '1:863346724834:ios:89894fb3d4575d6589f3bb',
    messagingSenderId: '863346724834',
    projectId: 'personal-portfolio-70dcc',
    storageBucket: 'personal-portfolio-70dcc.appspot.com',
    iosClientId: '863346724834-2j299kqg1d5qd8klli20badsc1ql5h39.apps.googleusercontent.com',
    iosBundleId: 'com.mnl.personalPortfolio.RunnerTests',
  );
}
